Repository AY2122S2-CS2103-F09-1/tp, pull requests merged in 2022-03, with the labels that each got.

#21 Branch user guide
  docs/UserGuide.md
Labels: documentation

#28 Edit user guide 'update' function section
  docs/UserGuide.md
Labels: documentation

#40 Change person class in AB3 to fit MyGM
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Age.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/Height.java
  src/main/java/seedu/address/model/person/JerseyNumber.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Phone.java
  src/main/java/seedu/address/model/person/Weight.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Task, priority.High

#39 V1.2 adds Team Packages
  src/main/java/seedu/address/model/team/Team.java
  src/main/java/seedu/address/model/team/TeamList.java
  src/main/java/seedu/address/model/team/TeamName.java
Labels: type.Task, priority.High

#118 Update user stories in DG
  docs/DeveloperGuide.md
Labels: documentation

#144 Resolve date time format error
  src/main/java/seedu/address/model/schedule/ScheduleDateTime.java
Labels: bug

#150 Corrects new CI issue
  docs/diagrams/newdiagrams/Add.puml
  docs/diagrams/newdiagrams/Delete.puml
  docs/diagrams/newdiagrams/Edit.puml
  docs/diagrams/newdiagrams/View.puml
  src/main/java/seedu/address/logic/commands/ThemeCommand.java
  src/main/java/seedu/address/storage/JsonAdaptedSchedule.java
  src/main/resources/view/MainWindow.fxml
Labels: type.Task
